# network: {config: disabled}
network:
    version: 2
    renderer: networkd
    ethernets:
        ens18:
            addresses:
                - 172.27.6.23/24
            nameservers:
                search: [janus.kmn.ie]
                addresses: [172.27.6.21, 172.27.6.22]
            routes:
                - to: default
                  via: 172.27.6.20
